/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nyaruko166.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ADMIN
 */
public class SettingView extends javax.swing.JFrame {

    /**
     * Creates new form SettingFrame
     */
    public SettingView() {
        initComponents();
//        this.setIconImage(new ImageIcon("src/main/resources/ico/nya.png").getImage());
        CenteredFrame(this);
        readConfig();

    }

    private String steamDir = "";
    private String crackGameDir = "";
    private String steamGameDir = "";

    public String folderChooser() {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("C:\\Program Files (x86)\\Steam"));
        chooser.setDialogTitle("Chọn folder Saved");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile().getName().contains("Saved")) {
                return chooser.getSelectedFile().getPath();
            } else {
                JOptionPane.showMessageDialog(this, "Vcl đã bảo chọn folder Saved rồi mà?", "Có biết đọc không?", JOptionPane.ERROR_MESSAGE);
                return null;
            }

        }
        return null;
    }

    public Boolean validateDir() {
        if (steamDir == null || steamDir.isBlank()) {
            JOptionPane.showMessageDialog(this, "Vcl m deo thêm path thì t chuyển save kiểu buoi gì?", "Path steam.exe đâu?", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (crackGameDir == null || crackGameDir.isBlank()) {
            JOptionPane.showMessageDialog(this, "Vcl m deo thêm path thì t chuyển save kiểu buoi gì?", "Path game crack đâu?", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (steamGameDir == null || steamGameDir.isBlank()) {
            JOptionPane.showMessageDialog(this, "Vcl m deo thêm path thì t chuyển save kiểu buoi gì?", "Path game steam đâu?", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }

    public void readConfig() {
        try {
            File f = new File("./config.txt");
            if (f.exists() && !f.isDirectory()) {
                FileReader fr = new FileReader("config.txt");
                BufferedReader br = new BufferedReader(fr);

                for (int i = 0; i < 3; i++) {
                    if (i == 0) {
                        steamDir = br.readLine();
                    } else if (i == 1) {
                        crackGameDir = br.readLine();
                    } else {
                        steamGameDir = br.readLine();
                    }
                }
                br.close();
                fr.close();
            } else {
                File file = new File("config.txt");
                file.createNewFile();
            }

        } catch (IOException ex) {
            Logger.getLogger(SettingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSteam = new javax.swing.JLabel();
        btnSteam = new javax.swing.JButton();
        btnCrack = new javax.swing.JButton();
        lblCrack = new javax.swing.JLabel();
        lblSteam1 = new javax.swing.JLabel();
        btnSteamDir = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setting Nè");

        lblSteam.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblSteam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSteam.setText("Steam");
        lblSteam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSteam.setText("Browse");
        btnSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteamActionPerformed(evt);
            }
        });

        btnCrack.setText("Browse");
        btnCrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrackActionPerformed(evt);
            }
        });

        lblCrack.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblCrack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrack.setText("Crack");
        lblCrack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSteam1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblSteam1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSteam1.setText("Chọn steam.exe");
        lblSteam1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSteamDir.setText("Browse");
        btnSteamDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteamDirActionPerformed(evt);
            }
        });

        btnSave.setText("Save Config");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCrack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrack)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSteam)
                        .addGap(18, 18, 18)
                        .addComponent(lblSteam1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSteamDir)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSteam1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSteamDir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteamActionPerformed
        steamGameDir = folderChooser();
    }//GEN-LAST:event_btnSteamActionPerformed

    private void btnCrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrackActionPerformed
        crackGameDir = folderChooser();
    }//GEN-LAST:event_btnCrackActionPerformed

    private void btnSteamDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteamDirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("File có đuôi là .exe", "exe"));
        chooser.setDialogTitle("Chọn file steam.exe");
        chooser.setCurrentDirectory(new java.io.File("C:\\Program Files (x86)"));
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile().getName().contains("steam")) {
                steamDir = chooser.getSelectedFile().getPath();
            } else {
                JOptionPane.showMessageDialog(this, "Vcl đã bảo chọn steam.exe mà?", "Ew khong biet doc?", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSteamDirActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (validateDir()) {
            try {
                FileWriter fw = new FileWriter("config.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(steamDir);
                bw.newLine();
                bw.write(crackGameDir);
                bw.newLine();
                bw.write(steamGameDir);

                bw.close();
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(SettingView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Save xong rồi nè ;b");
            this.dispose();
            new ViewFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSteam;
    private javax.swing.JButton btnSteamDir;
    private javax.swing.JLabel lblCrack;
    private javax.swing.JLabel lblSteam;
    private javax.swing.JLabel lblSteam1;
    // End of variables declaration//GEN-END:variables
}
